sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
linkReplacements:
  - "https://eclipse-ee4j.github.io/jsonb-api|https://github.com/eclipse-ee4j/jsonb-api"
build:
  exasolDbVersions:
    #- "8.29.1" # Will be added once exasol-testcontainers 7.1.1 is released, see https://github.com/exasol/bucketfs-java/issues/71
    - "7.1.29"
