sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
linkReplacements:
  - "https://eclipse-ee4j.github.io/jsonb-api|https://github.com/eclipse-ee4j/jsonb-api"
build:
  exasolDbVersions:
    # Build with Exasol 8 fails, see https://github.com/exasol/bucketfs-java/issues/66
    - "7.1.25"
