language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: exasol
    token:
       secure: "jqjLo57cGVabsH7MNI8egvoLrbqBshXzasWLXlcAoEFgdqstz0W1THEzxstbwgxwlMPgI6TQxPrCAH5CT2Fd/gCFAv8HXLm7MmCRt1dth/XNcU9a21XOaCtoRyu0T2xzqQ1AYVVa2O+74W3RL9oNhfAmNkZ100HxZjEAZEhO4iM7X9SCXo5Jmd82RrbqGRKjtd4kFik+i/MnAz2jpW8HM58Wk9w6/umZBMUdD5pKHiBN7VzTzZrISKMgRq0zbSbNIxMic4en/D3FxGBBXT0YFQCm9Mr8gicWCRosCrv95vODD72Lz9LfCB3EKBJbJ+Bzkw+8s1w7dsUNfJXeEDUAvHn7YH/pk6c4nqKbDpaI8Z6KASbAZd2Vn5znnWflOcaB5nQVffu/fHHtyzyOVvv+ERwMuczeqp6agTtcd1rfMzctFoEdZcgdv1vU5QPmzr0qOuMIwvrH2a6mXAnnVte/M3TW067tRW55ahEmyLtzaw7FykdpKs/jxmBzXxcCN7i3bSI+gj6vO1MmEDgKQPcJ2NjJ6th3H3+UMYROfEexczkfGX/6t2f7JjiR1IHqcP3RINGSPGpxbeOMuZcRId2rXcxzBjF286eQ6Dfult7jgggI2DujBUqavLicXdlkkDh88BIb8XLrm7hAFjkbOvQd/eTNw+q17+27KmJoavwN188="

install:
  - travis_retry mvn dependency:resolve

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - "$HOME/.m2"