language: java

jdk:
  - openjdk11

env:
  - DOCKER_DB_VERSION=7.0.6

addons:
  sonarcloud:
    organization: exasol

# Create an empty Docker config to avoid error message about missing config.
before_script:
  - mkdir "$HOME"/.docker
  - echo '{}' > "$HOME"/.docker/config.json
  - echo 'docker.client.strategy=org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy' > "$HOME"/.testcontainers.properties
  - echo 'testcontainers.reuse.enable=true' >> "$HOME"/.testcontainers.properties

install:
  - travis_retry mvn dependency:resolve

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:prepare-agent-integration
    verify sonar:sonar
    -Pexpensive
    -Dsonar.login=${SONAR_TOKEN}
    -Dtest.coverage="true"
    -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml
    -Dcom.exasol.dockerdb.image=${DOCKER_DB_VERSION}

cache:
  directories:
    - "$HOME/.m2"