language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: exasol

# Create an empty Docker config to avoid error message about missing config.
before_script:
  - mkdir "$HOME"/.docker
  - echo '{}' > "$HOME"/.docker/config.json
  - echo 'docker.client.strategy=org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy' > "$HOME"/.testcontainers.properties
  - echo 'testcontainers.reuse.enable=true' >> "$HOME"/.testcontainers.properties

install:
  - travis_retry mvn dependency:resolve

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - "$HOME/.m2"